services:
  - type: web
    name: appointment-system-backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: FRONTEND_URL
        value: https://client-q1z759bd7-kappativivekananda-7002s-projects.vercel.app
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
