version: "1"
services:
  - type: web
    name: appointment
    runtime: node
    rootDir: server
    repo: https://github.com/vivek-1728/appointment
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: node index.js
    autoDeployTrigger: commit
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: FRONTEND_URL
        value: https://client-q1z759bd7-kappativivekananda-7002s-projects.vercel.app
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
